Add config option to empty whole queue on flush
NewMotion/akka-statsd pull request #14
Opened 2017-08-25 16:50 UTC by Horneth

Hi !
We're adding statsd instrumentation to our workflow engine (https://github.com/broadinstitute/cromwell) and we'd like to use your code :)

We would like to take advantage of the multi-metric batching, my only concern is that under very heavy load it would be possible for the queue to grow out of control (considering a transmit interval of 100ms it means only 10 flushes / second). We could lower the interval or increase the number of Stats actors to mitigate that risk but I would like to be sure that the queue can't grow indefinitely if the load is too high and would rather lose packets to the network.

I was wondering if you would consider accepting this PR that adds an option to empty the entire queue on each flush.

I'm of course open to any feedback, requests you have (or if you think it's a bad idea don't hesitate to let me know either 😄 )

Thank you !

2017-08-29 09:44 UTC, poohsen commented on akka-statsd-core/src/test/scala/transport/MultiMetricQueueFunSpec.scala
> +        val subject = MultiMetricQueue(4).enqueue("12").enqueue("34").enqueue("56").enqueue("7")
So this is a packet_size of 4 and a queue with 4 elements. I don't see how that fits the test description?

2017-08-29 12:05 UTC, poohsen requested changes

2017-08-29 12:05 UTC, poohsen commented on akka-statsd-core/src/test/scala/transport/ScheduledDispatcherSpec.scala
> +  private class Environment(transmitInterval: Long, emptyQueueOnFlush: Boolean = false) {
this looks redundant to me

2017-09-04 08:36 UTC, poohsen commented
hi @Horneth , can you make the change? then I'll be happy to merge your PR

2017-09-05 13:33 UTC, Horneth commented
Sorry I've been busy with unrelated work. Sure I'll do that today. Thanks !

2017-09-06 09:22 UTC, poohsen approved these changes

2017-09-06 09:22 UTC, merged

2017-09-06 09:23 UTC, poohsen commented
Merged. Please not that we're currently experiencing difficulties with our sonatype connection so I cannot provide a release via sonatype.